//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureVault.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keys
    {
        public int V_ID { get; set; }
        public int ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public bool Hidden { get; set; }
    
        public virtual Vaults Vaults { get; set; }
    }
}
