//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureVault.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecureVaultDataEntities : DbContext
    {
        public SecureVaultDataEntities()
            : base("name=SecureVaultDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Keys> Keys { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vaults> Vaults { get; set; }
    }
}
